app = "host-langflow-mg24tw"
primary_region = "bom"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

[[vm]]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 2
